Feature generate qrcode
DESQOL/MyCoeliac pull request #70
Opened 2019-12-25 04:05 UTC by Walorda

Android components should be placed in android files ---- is broken

2019-12-25 08:18 UTC, mvegter requested changes

2019-12-25 08:18 UTC, mvegter commented on src/screens/qrcode_generator/Test.tsx
> +     *  ADDED IT IN COMMENTS BECAUSE FUCKING ESLINT + REACT NATIVE + TYPESCRIPT IS A CANCEROUS FUCKING TUMOR
...

2019-12-25 08:18 UTC, mvegter commented on src/navigations/Navigation.tsx
> +
?

2019-12-25 08:18 UTC, mvegter commented on src/screens/qrcode_generator/QrcodeGenerator.ios.tsx
> + * Make the component invissble or hidden and call the fucking requestcamera which in turns makes the qr code when
...

2019-12-25 08:18 UTC, mvegter commented on src/screens/qrcode_generator/QrcodeGenerator.android.tsx
> + * Make the component invissble or hidden and call the fucking requestcamera which in turns makes the qr code when
...

2019-12-30 14:27 UTC, Jordy-Boelhouwer commented on src/screens/qrcode_generator/QrcodeGenerator.android.tsx
> +                  buttonNeutral: 'Ask Me Later',
Is the neutral option neccesary?

2019-12-30 14:30 UTC, Jordy-Boelhouwer requested changes

2019-12-30 14:30 UTC, Jordy-Boelhouwer commented on src/screens/qrcode_generator/QrcodeGenerator.ios.tsx
> +                  console.log('test');
Remove the logs if you are done testing

2019-12-30 14:30 UTC, Jordy-Boelhouwer commented on src/screens/qrcode_generator/QrcodeGenerator.android.tsx
> +                  buttonNeutral: 'Ask Me Later',
Is the neutral option neccesary?

2020-01-05 15:35 UTC, mvegter commented
@Walorda ping

2020-01-06 07:02 UTC, mvegter commented
Ping @Walorda

@Jordy-Boelhouwer Can I get your opinion regarding the (error) eslint issues.

2020-01-06 08:49 UTC, mvegter commented
@Walorda @Jordy-Boelhouwer does the `barcode_scanner` match the naming convention?

2020-01-06 10:28 UTC, mvegter approved these changes

2020-01-06 10:37 UTC, merged